name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4.2.2

      - name: Set up JDK
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '21'
          distribution: temurin
          cache: maven

      - name: Clear target folder
        run: rm -r target

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Copy artifacts
        run: |
          JAR_FILE=$(find target -name "*.jar" -type f | head -n 1)
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV
          echo "$JAR_FILE"
          cp "$JAR_FILE" ./RestartAR.jar

      - name: Upload bundle
        uses: actions/upload-artifact@v4.6.2
        with:
          name: RestartAR-build
          path: RestartAR.jar
